/// Flutter icons FigmaIcon
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.

import 'package:flutter/widgets.dart';

class FigmaIcon {
  FigmaIcon._();

  static const _kFontFam = 'FigmaIcon';
  static const String? _kFontPkg = null;

  static const IconData notification_icon =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
